import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/plant_type_model.dart';

class PlantTypeService {
  static const _collection = 'plant_types';
  final _db = FirebaseFirestore.instance;

  // Scientifically-backed tolerance and agronomic data.
  // Temperature/humidity sources: FAO Crop Production Guidelines, USDA Plant
  // Hardiness, Hochmuth et al. (UF/IFAS), and horticultural references.
  // Best-month data is calibrated for the Indonesian tropical climate
  // (Jakarta reference): wet season Oct–Mar, dry season Apr–Sep.
  static const List<PlantTypeModel> _seedData = [
    PlantTypeModel(
      id: 'selada',
      name: 'Selada',
      emoji: '🥬',
      minTemp: 7,
      maxTemp: 24,
      minHumidity: 60,
      maxHumidity: 70,
      bestMonths: [1, 2, 3, 9, 10, 11, 12],
      plantingTip: 'Tanam di bulan sejuk, hindari panas terik siang hari',
      difficulty: 'Mudah',
      benefits: ['Panen cepat 30–45 hari', 'Kaya vitamin K & folat', 'Cocok sistem hidroponik'],
      reason: 'Tumbuh optimal pada suhu sejuk 7–24°C, ideal ditanam di awal/akhir tahun yang lebih sejuk',
    ),
    PlantTypeModel(
      id: 'tomat',
      name: 'Tomat',
      emoji: '🍅',
      minTemp: 15,
      maxTemp: 34,
      minHumidity: 60,
      maxHumidity: 85,
      bestMonths: [4, 5, 6, 7, 8, 9],
      plantingTip: 'Butuh musim kering untuk pembuahan optimal, hindari genangan',
      difficulty: 'Sedang',
      benefits: ['Kaya likopen & vitamin C', 'Nilai ekonomi tinggi', 'Bisa di pot besar'],
      reason: 'Pembungaan dan pembuahan optimal saat curah hujan rendah di musim kemarau',
    ),
    PlantTypeModel(
      id: 'cabai',
      name: 'Cabai',
      emoji: '🌶️',
      minTemp: 20,
      maxTemp: 35,
      minHumidity: 50,
      maxHumidity: 85,
      bestMonths: [3, 4, 5, 6, 7, 8],
      plantingTip: 'Tumbuh optimal di musim kemarau, hindari genangan air di akar',
      difficulty: 'Sedang',
      benefits: ['Nilai ekonomi tinggi', 'Buah terus-menerus', 'Tahan panas tropis'],
      reason: 'Produksi buah terbaik saat suhu 24–35°C dan kelembapan tidak terlalu tinggi',
    ),
    PlantTypeModel(
      id: 'paprika',
      name: 'Paprika',
      emoji: '🫑',
      minTemp: 18,
      maxTemp: 28,
      minHumidity: 65,
      maxHumidity: 80,
      bestMonths: [4, 5, 6, 7, 8],
      plantingTip: 'Butuh suhu konsisten 18–28°C, sangat cocok dalam greenhouse',
      difficulty: 'Sulit',
      benefits: ['Kaya vitamin A & C', 'Nilai ekonomi premium', 'Warna menarik'],
      reason: 'Optimal di musim kering, rentan penyakit jamur jika kelembapan terlalu tinggi',
    ),
    PlantTypeModel(
      id: 'timun',
      name: 'Timun',
      emoji: '🥒',
      minTemp: 21,
      maxTemp: 32,
      minHumidity: 70,
      maxHumidity: 90,
      bestMonths: [4, 5, 6, 7, 8, 9],
      plantingTip: 'Tumbuh cepat di cuaca hangat, perlu ajir atau rambatan vertikal',
      difficulty: 'Mudah',
      benefits: ['Panen cepat 35–40 hari', 'Tinggi air & elektrolit', 'Cocok vertikal garden'],
      reason: 'Perkecambahan dan pertumbuhan cepat di suhu 24–32°C musim kemarau',
    ),
    PlantTypeModel(
      id: 'pakcoy',
      name: 'Pakcoy',
      emoji: '🥬',
      minTemp: 15,
      maxTemp: 25,
      minHumidity: 65,
      maxHumidity: 75,
      bestMonths: [1, 2, 3, 9, 10, 11, 12],
      plantingTip: 'Tumbuh cepat di suhu sejuk, sangat cocok sistem hidroponik NFT',
      difficulty: 'Mudah',
      benefits: ['Panen 30 hari', 'Kaya kalsium & vitamin C', 'Cocok hidroponik'],
      reason: 'Toleran suhu rendah, ideal ditanam saat awal/akhir tahun yang lebih sejuk',
    ),
    PlantTypeModel(
      id: 'bayam',
      name: 'Bayam',
      emoji: '🍃',
      minTemp: 15,
      maxTemp: 35,
      minHumidity: 50,
      maxHumidity: 85,
      bestMonths: [1, 2, 3, 4, 10, 11, 12],
      plantingTip: 'Tumbuh cepat 3 minggu, butuh penyiraman rutin pagi dan sore',
      difficulty: 'Mudah',
      benefits: ['Panen 20–30 hari', 'Kaya zat besi & protein nabati', 'Bisa dipanen berkali-kali'],
      reason: 'Bayam (Amaranthus) sangat adaptif di iklim tropis lembap, tumbuh optimal di kondisi lembap',
    ),
    PlantTypeModel(
      id: 'kangkung',
      name: 'Kangkung',
      emoji: '🌿',
      minTemp: 25,
      maxTemp: 40,
      minHumidity: 70,
      maxHumidity: 95,
      bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      plantingTip: 'Bisa ditanam sepanjang tahun, tumbuh subur di kondisi lembap dan panas',
      difficulty: 'Mudah',
      benefits: ['Tumbuh cepat 3–4 minggu', 'Kaya zat besi & vitamin A', 'Minim perawatan'],
      reason: 'Tahan suhu panas tropis hingga 40°C, sangat adaptif untuk iklim Indonesia',
    ),
    PlantTypeModel(
      id: 'sawi',
      name: 'Sawi',
      emoji: '🥬',
      minTemp: 15,
      maxTemp: 25,
      minHumidity: 60,
      maxHumidity: 75,
      bestMonths: [1, 2, 3, 9, 10, 11, 12],
      plantingTip: 'Suka suhu sejuk dan lembap, hindari paparan sinar matahari siang penuh',
      difficulty: 'Mudah',
      benefits: ['Panen 30–40 hari', 'Kaya vitamin K & kalsium', 'Cocok di pot kecil'],
      reason: 'Tumbuh optimal di suhu 15–25°C, cocok ditanam di musim penghujan',
    ),
    PlantTypeModel(
      id: 'terong',
      name: 'Terong',
      emoji: '🍆',
      minTemp: 20,
      maxTemp: 35,
      minHumidity: 55,
      maxHumidity: 85,
      bestMonths: [3, 4, 5, 6, 7, 8, 9, 10],
      plantingTip: 'Tumbuh subur di cuaca panas, butuh sinar matahari minimal 6 jam per hari',
      difficulty: 'Sedang',
      benefits: ['Produksi buah berlimpah', 'Kaya antioksidan nasunin', 'Cocok media tanah'],
      reason: 'Produktif di musim kering-kemarau, tahan suhu panas tropis 25–35°C',
    ),
    PlantTypeModel(
      id: 'stroberi',
      name: 'Stroberi',
      emoji: '🍓',
      minTemp: 15,
      maxTemp: 26,
      minHumidity: 65,
      maxHumidity: 75,
      bestMonths: [5, 6, 7, 8, 9],
      plantingTip: 'Butuh suhu sejuk, cocok di dataran tinggi atau pot dalam ruangan ber-AC',
      difficulty: 'Sulit',
      benefits: ['Kaya vitamin C & antioksidan', 'Nilai jual tinggi', 'Cocok pot vertikal'],
      reason: 'Pembuahan optimal di suhu 15–22°C saat musim kering, rentan di cuaca panas lembap',
    ),
    PlantTypeModel(
      id: 'jagung',
      name: 'Jagung',
      emoji: '🌽',
      minTemp: 18,
      maxTemp: 35,
      minHumidity: 50,
      maxHumidity: 80,
      bestMonths: [3, 4, 5, 9, 10, 11],
      plantingTip: 'Butuh ruang vertikal, cocok ditanam awal atau akhir musim kemarau',
      difficulty: 'Sedang',
      benefits: ['Kaya karbohidrat & serat', 'Panen 60–90 hari', 'Dekoratif di taman'],
      reason: 'Perkecambahan optimal saat suhu tanah 20–32°C, produktif di awal musim kering',
    ),
    PlantTypeModel(
      id: 'kentang',
      name: 'Kentang',
      emoji: '🥔',
      minTemp: 10,
      maxTemp: 25,
      minHumidity: 60,
      maxHumidity: 80,
      bestMonths: [4, 5, 6, 7, 8],
      plantingTip: 'Butuh tanah gembur dan sejuk, cocok grow bag besar di dataran tinggi',
      difficulty: 'Sedang',
      benefits: ['Kaya karbohidrat kompleks', 'Tahan simpan lama', 'Bisa di grow bag besar'],
      reason: 'Pembentukan umbi optimal saat suhu 15–20°C, perkembangan terbaik di musim kering',
    ),
    PlantTypeModel(
      id: 'kedelai',
      name: 'Kedelai',
      emoji: '🫘',
      minTemp: 20,
      maxTemp: 35,
      minHumidity: 50,
      maxHumidity: 80,
      bestMonths: [3, 4, 5, 6, 7, 8, 9, 10],
      plantingTip: 'Tumbuh optimal di awal kemarau, butuh sinar matahari penuh seharian',
      difficulty: 'Sedang',
      benefits: ['Kaya protein nabati lengkap', 'Menyuburkan tanah (nitrogen)', 'Cocok rotasi tanaman'],
      reason: 'Legum pengikat nitrogen, produktif di musim kering dengan curah hujan terbatas',
    ),
    PlantTypeModel(
      id: 'labu',
      name: 'Labu',
      emoji: '🎃',
      minTemp: 18,
      maxTemp: 35,
      minHumidity: 55,
      maxHumidity: 80,
      bestMonths: [4, 5, 6, 7, 8, 9],
      plantingTip: 'Merambat panjang, cocok untuk pergola, pagar, atau media vertikal',
      difficulty: 'Mudah',
      benefits: ['Panen besar & memuaskan', 'Kaya beta-karoten', 'Tahan lama pasca-panen'],
      reason: 'Tumbuh pesat di musim kering, toleran suhu tinggi 25–35°C dengan drainase baik',
    ),
    PlantTypeModel(
      id: 'apel',
      name: 'Apel',
      emoji: '🍎',
      minTemp: 7,
      maxTemp: 24,
      minHumidity: 60,
      maxHumidity: 70,
      bestMonths: [5, 6, 7, 8],
      plantingTip: 'Butuh suhu dingin untuk pembungaan, cocok dataran tinggi di atas 1000 mdpl',
      difficulty: 'Sulit',
      benefits: ['Nilai ekonomi premium', 'Buah segar bergizi', 'Investasi jangka panjang'],
      reason: 'Memerlukan vernalisasi (pendinginan), hanya cocok untuk daerah pegunungan tropis',
    ),
    PlantTypeModel(
      id: 'anggur',
      name: 'Anggur',
      emoji: '🍇',
      minTemp: 15,
      maxTemp: 30,
      minHumidity: 50,
      maxHumidity: 75,
      bestMonths: [4, 5, 6, 7, 8, 9],
      plantingTip: 'Butuh pergola dan musim kering panjang, pangkas setelah masa dormansi',
      difficulty: 'Sulit',
      benefits: ['Hasil melimpah jika dirawat', 'Kaya antioksidan resveratrol', 'Mempercantik taman'],
      reason: 'Pembuahan optimal di musim kering, membutuhkan periode dormansi untuk produksi buah',
    ),
    PlantTypeModel(
      id: 'jeruk',
      name: 'Jeruk',
      emoji: '🍊',
      minTemp: 13,
      maxTemp: 35,
      minHumidity: 60,
      maxHumidity: 80,
      bestMonths: [3, 4, 5, 6, 7, 8, 9, 10],
      plantingTip: 'Pohon tahunan, pembungaan terpicu setelah periode kering singkat (stress air)',
      difficulty: 'Sedang',
      benefits: ['Buah tahan lama', 'Kaya vitamin C', 'Cocok balkon atau taman luas'],
      reason: 'Pembungaan terbaik setelah periode kekeringan singkat, panen 6–9 bulan kemudian',
    ),
    PlantTypeModel(
      id: 'blueberry',
      name: 'Blueberry',
      emoji: '🫐',
      minTemp: 13,
      maxTemp: 24,
      minHumidity: 55,
      maxHumidity: 75,
      bestMonths: [5, 6, 7, 8],
      plantingTip: 'Butuh pH tanah 4.5–5.5, cocok pot khusus dengan media asam di ruangan sejuk',
      difficulty: 'Sulit',
      benefits: ['Kaya antioksidan tertinggi', 'Nilai jual premium', 'Superfood populer'],
      reason: 'Tumbuh optimal di suhu 13–24°C, sulit di dataran rendah tropis tanpa kontrol suhu',
    ),
    PlantTypeModel(
      id: 'raspberry',
      name: 'Raspberry',
      emoji: '🍒',
      minTemp: 13,
      maxTemp: 24,
      minHumidity: 60,
      maxHumidity: 70,
      bestMonths: [5, 6, 7, 8],
      plantingTip: 'Butuh kondisi sejuk, paling cocok di pot dalam ruangan atau greenhouse berpendingin',
      difficulty: 'Sulit',
      benefits: ['Kaya vitamin C & mangan', 'Nilai jual tinggi', 'Antioksidan superfood'],
      reason: 'Memerlukan suhu malam 10–18°C untuk pembungaan, sulit tanpa kontrol lingkungan',
    ),
    PlantTypeModel(
      id: 'persik',
      name: 'Persik',
      emoji: '🍑',
      minTemp: 15,
      maxTemp: 25,
      minHumidity: 55,
      maxHumidity: 75,
      bestMonths: [5, 6, 7, 8],
      plantingTip: 'Butuh akumulasi chilling hours, lebih cocok dataran tinggi Jawa atau Sumatra',
      difficulty: 'Sulit',
      benefits: ['Buah eksotis bergizi', 'Nilai jual premium', 'Cantik saat berbunga'],
      reason: 'Memerlukan 400–800 jam di bawah 7°C untuk pembungaan, sulit di dataran rendah',
    ),
    PlantTypeModel(
      id: 'kemangi',
      name: 'Kemangi',
      emoji: '🌱',
      minTemp: 20,
      maxTemp: 35,
      minHumidity: 45,
      maxHumidity: 80,
      bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      plantingTip: 'Tumbuh baik sepanjang tahun, pangkas pucuk bunga agar daun terus tumbuh rimbun',
      difficulty: 'Mudah',
      benefits: ['Aroma segar usir serangga', 'Kaya vitamin K & antioksidan', 'Cocok pot kecil windowsill'],
      reason: 'Toleran suhu tropis tinggi 20–35°C, aromatik dan berfungsi sebagai penolak serangga alami',
    ),
    PlantTypeModel(
      id: 'brokoli',
      name: 'Brokoli',
      emoji: '🥦',
      minTemp: 7,
      maxTemp: 24,
      minHumidity: 60,
      maxHumidity: 80,
      bestMonths: [4, 5, 6, 7, 8, 9],
      plantingTip: 'Butuh suhu malam sejuk untuk pembentukan kepala brokoli yang rapat',
      difficulty: 'Sedang',
      benefits: ['Superfood kaya sulforafan', 'Cocok pot sedang', 'Kepala kompak di cuaca sejuk'],
      reason: 'Pembentukan curd (kepala) optimal di suhu 15–20°C, membutuhkan perbedaan suhu siang-malam',
    ),
    PlantTypeModel(
      id: 'wortel',
      name: 'Wortel',
      emoji: '🥕',
      minTemp: 10,
      maxTemp: 25,
      minHumidity: 60,
      maxHumidity: 80,
      bestMonths: [7, 8, 9, 10],
      plantingTip: 'Butuh tanah dalam dan gembur untuk akar lurus, kurangi air berlebih',
      difficulty: 'Sedang',
      benefits: ['Kaya beta-karoten', 'Tahan simpan lama', 'Cocok deep container / grow bag'],
      reason: 'Pertumbuhan akar optimal di suhu 15–20°C saat musim kering dengan drainase baik',
    ),
    PlantTypeModel(
      id: 'lainnya',
      name: 'Lainnya',
      emoji: '',
      minTemp: 15,
      maxTemp: 35,
      minHumidity: 50,
      maxHumidity: 85,
      bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      plantingTip: 'Sesuaikan perawatan dengan kebutuhan spesifik jenis tanaman',
      difficulty: 'Sedang',
      benefits: ['Fleksibel untuk berbagai tanaman', 'Sesuai kebutuhan personal'],
      reason: 'Kategori umum untuk tanaman yang belum tercantum dalam daftar',
    ),
  ];

  Future<List<PlantTypeModel>> fetchAll() async {
    final snap = await _db.collection(_collection).orderBy('name').get();
    return snap.docs.map((d) => PlantTypeModel.fromMap(d.data())).toList();
  }

  /// Seeds - or re-seeds when the existing data is missing the new agronomic
  /// fields (detected by absence of 'difficulty' on the first document).
  Future<void> seedIfEmpty() async {
    final snap = await _db.collection(_collection).limit(1).get();
    final alreadyMigrated =
        snap.docs.isNotEmpty && snap.docs.first.data().containsKey('difficulty');
    if (alreadyMigrated) return;

    final batch = _db.batch();
    for (final type in _seedData) {
      final ref = _db.collection(_collection).doc(type.id);
      batch.set(ref, type.toMap());
    }
    await batch.commit();
  }
}
