// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDFil5jvySJ06vRjTPzTBMQuibyov1xRo',
    appId: '1:464823614734:web:1df33acadec74b2c33ab5f',
    messagingSenderId: '464823614734',
    projectId: 'urban-leaf-2bc3a',
    authDomain: 'urban-leaf-2bc3a.firebaseapp.com',
    storageBucket: 'urban-leaf-2bc3a.firebasestorage.app',
    measurementId: 'G-S0HGYJ4ZTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgYATkLT7JsCanr9JtyGrD127GkrUkVc',
    appId: '1:464823614734:android:db69472714ef41cd33ab5f',
    messagingSenderId: '464823614734',
    projectId: 'urban-leaf-2bc3a',
    storageBucket: 'urban-leaf-2bc3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqaiPV3W31cQgRhOvpwbzQ60HvLpVPzmE',
    appId: '1:464823614734:ios:dc7065e1d91d0be733ab5f',
    messagingSenderId: '464823614734',
    projectId: 'urban-leaf-2bc3a',
    storageBucket: 'urban-leaf-2bc3a.firebasestorage.app',
    iosBundleId: 'com.example.urbanLeaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqaiPV3W31cQgRhOvpwbzQ60HvLpVPzmE',
    appId: '1:464823614734:ios:dc7065e1d91d0be733ab5f',
    messagingSenderId: '464823614734',
    projectId: 'urban-leaf-2bc3a',
    storageBucket: 'urban-leaf-2bc3a.firebasestorage.app',
    iosBundleId: 'com.example.urbanLeaf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDFil5jvySJ06vRjTPzTBMQuibyov1xRo',
    appId: '1:464823614734:web:80da0b5fc4db699133ab5f',
    messagingSenderId: '464823614734',
    projectId: 'urban-leaf-2bc3a',
    authDomain: 'urban-leaf-2bc3a.firebaseapp.com',
    storageBucket: 'urban-leaf-2bc3a.firebasestorage.app',
    measurementId: 'G-HMS6HJ8XEF',
  );

}